return {
  -- trailing space: lualine and signs want a 2-cell symbol; neo-tree trims it
  git = {
    added     = "󰐕 ",
    modified  = "󰏫 ",
    removed   = "󰍴 ",
    renamed   = "󰁅 ",
    untracked = "󰋖 ",
    ignored   = "󰈉 ",
    conflict  = "󰘬 ",
    unstaged  = "󰄱 ",
    staged    = "󰱒 ",
  },
  -- octicons
  diagnostics = {
    Error = " ",
    Warn  = " ",
    Hint  = " ",
    Info  = " ",
  },
  -- Material; blink adds its own gap after the icon
  kinds = {
    Array         = "󰅪",
    Boolean       = "󰨙",
    Class         = "󰆧",
    Color         = "󰏘",
    Constant      = "󰏿",
    Constructor   = "󰒓",
    Enum          = "󰦨",
    EnumMember    = "󰦨",
    Event         = "󱐋",
    Field         = "󰜢",
    File          = "󰈙",
    Folder        = "󰉋",
    Function      = "󰊕",
    Interface     = "󰕘",
    Key           = "󰌋",
    Keyword       = "󰻾",
    Method        = "󰊕",
    Module        = "󰅩",
    Namespace     = "󰦮",
    Null          = "󰟢",
    Number        = "󰎠",
    Object        = "󰅩",
    Operator      = "󰆕",
    Package       = "󰏗",
    Property      = "󰖷",
    Reference     = "󰬲",
    Snippet       = "󱄽",
    String        = "󰉾",
    Struct        = "󰆼",
    Text          = "󰉿",
    TypeParameter = "󰗴",
    Unit          = "󰪚",
    Value         = "󰦨",
    Variable      = "󰀫",
  },
  -- Material; neo-tree icon component
  folders = {
    closed       = "󰉋",
    open         = "󰝰",
    empty        = "󰉖",
    empty_open   = "󰷏",
    default_file = "󰈔",
  },
}
