vim.g.loaded_netrw = 1 -- disable built-in file explorer (netrw) in favor of neo-tree
vim.g.loaded_netrwPlugin = 1
vim.g.mapleader = "," -- leader key
vim.g.maplocalleader = "\\" -- leader key

vim.o.mouse = "a" -- mouse support
vim.o.shell = "/bin/zsh"
vim.o.whichwrap = vim.o.whichwrap .. "<,>,h,l" -- Wrap movement between lines in edit mode with arrows
vim.wo.colorcolumn = "120" -- shows vertical bar

local opt = vim.opt

opt.clipboard = vim.env.SSH_CONNECTION and "" or "unnamedplus" -- Sync with system clipboard
opt.undofile = true -- save undo changes between sessions
opt.writebackup = false -- does not make a backup before overwriting a file
opt.swapfile = false -- does not use swapfile for the buffer
opt.title = true -- show filename in title
opt.scrolloff = 4 -- minimum indentation from top/bottom of screen to highlighted result on searching
opt.sidescrolloff = 8 -- Columns of context
opt.number = true -- print the line number in front of each line
opt.rnu = true -- print relative line numbers
opt.history = 1000 -- size of the saved command-lines in a history table
opt.wrap = false -- disable wrapping strings (when they are very long)
opt.list = true -- show tabs as CTRL-I is displayed
opt.listchars = "tab:▷⋅,trail:⋅,nbsp:⋅" -- strings to use in 'list' mode
opt.splitbelow = true -- open split window below
opt.splitright = true -- open split window right
opt.confirm = true -- Confirm to save changes before exiting modified buffer
opt.cursorcolumn = true -- highlights whole column under cursor
opt.cursorline = true -- highlights whole line under cursor
opt.tabstop = 2 -- number of spaces for tab
opt.shiftwidth = 2 -- number of spaces to use for each step of (auto)indent
opt.shiftround = true -- Round indent
opt.smartindent = true -- Insert indents automatically
opt.softtabstop = 2 -- number of spaces that a <Tab> counts for while performing editing operations
opt.expandtab = true -- use the appropriate number of spaces to insert a <Tab> in the insert mode
opt.ignorecase = true -- ignore case in search patterns
opt.smartcase = true -- override the 'ignorecase' option if the search pattern contains upper case characters
opt.fillchars = "vert:▏" -- characters to fill the statuslines and vertical separators
opt.diffopt = "filler,internal,algorithm:histogram,indent-heuristic,linematch:60" -- option settings for diff mode
opt.signcolumn = "yes" -- reserve a column for language client/gitgutter notifications even if nothing to show
opt.spelllang = { "en_gb" } -- set spell languages
opt.linebreak = true -- Stop words being broken on wrap
opt.showmode = false -- Don't display mode
opt.smoothscroll = true
opt.guicursor =
  "n-v-c-sm:block-blinkwait50-blinkon50-blinkoff50,i-ci-ve:ver25-Cursor-blinkon100-blinkoff100,r-cr-o:hor20" -- sets blinking guicursor
opt.foldmethod = "expr" -- use expression for folding
opt.foldexpr = "v:lua.vim.treesitter.foldexpr()" -- gives the fold level of a line.
opt.foldenable = true
opt.foldlevel = 99 -- all folds open, so `za` only touches the block under the cursor
opt.foldlevelstart = 99
opt.foldtext = "" -- folded line keeps treesitter highlighting
opt.wildmode = "longest:full,full" -- Command-line completion mode
opt.winminwidth = 5 -- Minimum window width
opt.winborder = "rounded" -- border for floating windows that do not set their own (hover, signature help, diagnostics)
opt.updatetime = 300 -- CursorHold after 300 ms: diagnostic float, illuminate

opt.wildignorecase = true -- wildmenu ignores case
